### ISSUE TITLE
A Savannah backend

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1037]
So I can put:
https://git.savannah.gnu.org/cgit/gnuzilla.git
Then have it sort out the pre-release stuff where applicable?

Here is an example of where it would be useful: https://release-monitoring.org/project/5609/
The GNU project backend doesn't have the latest packages, git does. This can't be the only package where this happens.

Would be useful thanks.

**Comment by Zlopez** [comment]
Git backend is actually too wide to implement correctly, but if you talking about Savannah backend, this could be done.

I clicked on the link you have in your message and it doesn't show anything `No repositories found`.

**Comment by romulasry** [comment]
Yes, Savannah would work. Sorry the repo is currently not working..

**Comment by erolkskn** [comment]
I think it should be "cgit" backend rather than "savannah" backend. That's because of this url (https://git.savannah.gnu.org/cgit/gnuzilla.git) is actually cgit url, and it's not special to savannah project. 

Few examples are: 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/refs/tags/?h=v5.18.15
- https://git.zx2c4.com/cgit/refs/tags

@Zlopez What do you think about that ? Btw i can implement cgit backend, if it's okay
