### ISSUE TITLE
curl releases not being fetched

### ISSUE THREAD

**Issue by vpodzime** [fedora-infra/anitya#1118]
https://release-monitoring.org/project/381/ shows new versions based on tags (e.g. 7_77_0), but since 7.74.0 there are no new versions based on releases (with dots instead of underscores). I tried some modifications and hitting *Test check*, but the releases (with dots) were never recognized as new versions.

**Comment by Zlopez** [comment]
The Anitya doesn't use releases for getting versions. This was tried in the past and it didn't work, because of the releases named by anything you can imagine, instead we are reading tag referenced by the release.
I looked at the curl recently and only way to get versions rid of the underscore is to convert this to custom backend. This way you can catch each part of the versions separately and the anitya will concatenate the groups with `.`.

I did this for you on https://release-monitoring.org/project/381/

**Comment by vpodzime** [comment]
Makes sense. Many thanks, @Zlopez!
