### ISSUE TITLE
libadwaita doesn't show the latest version: 1.0.0.alpha.3 

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1199]
https://release-monitoring.org/project/234898/
See:
https://gitlab.gnome.org/GNOME/libadwaita/-/tags/1.0.0.alpha.3

**Comment by Zlopez** [comment]
This looks like a bug in regex validation for GitLab backend. The new version differs from the previous ones by using `.` instead of `-`. See `1.0.0.alpha.3` against `1.0.0-alpha.2` . I need to check the regex for GitLab backend and see if the change in regex wouldn't introduce new issues.

As a workaround you can still use the custom backend, because there is a option to use your own regex for validation. Just change the backend, use the same URL for checking and update the regex to will match both version formats the project is using.

**Comment by Zlopez** [comment]
It seems that this was already fixed, I tried it on my local instance of release-monitoring.org and it retrieved even the mentioned version.

Closing the issue.
