### ISSUE TITLE
Github: Rate limit was reached. Will be reset in "2021-10-21T03:03:47+00:00".

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1210]
https://release-monitoring.org/project/2048/

**Comment by Zlopez** [comment]
This is correct, the GitHub has a ratelimit for the API calls for each hour. They will be added to queue and tried after rate limit will be reset. This could take multiple runs till the project will be able to pass again, because it's added at the end of the queue.
At the bottom of the page, you can see the output of latest check, how many projects were checked, how many passed, how many failed and how many was affected by GitHub ratelimit.
