### ISSUE TITLE
Detected new upstream version but got the download URL wrong

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/anitya#123]
In this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1206962, it correctly detected that a new version was available, however it got the download URL wrong and failed to find the new source. I think it's just using the SOURCE from the spec instead of the actual file that it found here?

**Comment by pypingou** [comment]
It does uses the Source0 from the spec file indeed.
Anitya can find a new version by multiple ways and quite often this way is not directly pointing to a tarball of some sort, so anitya only announces on the bus that a new version is available (and which version that is).

From there, the-new-hotness asks pkgdb if the package is set for monitoring, and if so then with the only information available of the new version, pulls the spec file from the git and tries to do a rebuild.

Does that clear things up?

**Comment by ralphbean** [comment]
Yeah, @sanjayankur31, it bumps the ``Version:`` tag in the spec and then tries to call ``spectool -g`` to download the new sources.  It looks like that ``Source0`` url needs to use the ``%{version}`` macro in more places so that the version bump can be automated.

The the hard-coded ``3.15`` here?  http://pkgs.fedoraproject.org/cgit/gnote.git/tree/gnote.spec#n8

**Comment by sanjayankur31** [comment]
Yeah, that's because the version is 3.15.X, but the URL only uses 3.15 for the folder name. For example, now the new version is 3.16.0, but the URL only has 3.16 and then minor releases under there. So, I can't use %{version} in the url there :(

**Comment by sanjayankur31** [comment]
Gah, but I forgot to update the URL in the spec to 3.16!

/me goes to fix it.
