### ISSUE TITLE
github-cli: Latest version from upstream is 2.5.2, but Anitya thinks its 9.9.9-test

### ISSUE THREAD

**Issue by ajhalili2006** [fedora-infra/anitya#1313]
## About this bug

Version `9.9.9-test` points to commit https://github.com/cli/cli/commit/bad38fdcfba505a439720128a9a2d7c9d3f694ef, which occurred more than an month ago while version `2.5.2` is [the more recent one.](https://github.com/cli/cli/releases/v2.5.2)

While it's possible that this might be an by-design issue on how Anitya chooses what's considered as latest version by highest number instead of release/Git tag creation date, I can probably notify GitHub CLI maintainers about this if that's not the case.

## Additional Context

* Project Page on hosted app: https://release-monitoring.org/project/135615/

**Comment by Zlopez** [comment]
The Anitya chooses the latest version based on the [version scheme](https://anitya.readthedocs.io/en/stable/user-guide.html#version-scheme), because the latest tag doesn't really mean the latest version, especially on projects that have multiple supported releases.

But for bogus releases we have [version filter](https://anitya.readthedocs.io/en/stable/user-guide.html#version-filter) in Anitya. So I fixed  the project by deleting the `9.9.9-test` version and adding `test` to `version filter` on the project, so it shouldn't be obtained again.
