### ISSUE TITLE
Anitya doesn't find versions for GitHub project with proper tags

### ISSUE THREAD

**Issue by PureTryOut** [fedora-infra/anitya#1832]
I just added https://github.com/maplibre/maplibre-native to Anitya and even though it has _a ton_ of tags, Anitya fails to find the ones relevant for Linux. The repo includes the tags `qt-v2.0.0` and `qt-v2.0.1` but Anitya only manages to find Android, iOS and Node related ones. Obviously I let Anitya filter those out but rather than then finding the Qt tags it just finds nothing instead.

I'm guessing due to the huge amount of tags GitHub starts paginating the list and Anitya doesn't try the other pages?

**Comment by Zlopez** [comment]
Anitya is only checking the last 50 tags on the GitHub repository. The reason for that is to not hit the ratelimit that often. I can advice to watch releases instead of tags, but I'm not sure if that will be helpful in this case as there is plenty of mobile versions on top of the Linux versions. Or if you care only about the new versions released it will work as you already set it up, looking for any new `qt-*` tag added to project.

You can also try to setup the custom backend, but it isn't the best solution. Could you provide a link to Anitya project, so I can look at it.

**Comment by PureTryOut** [comment]
I've since realized that the Qt version has been split off to it's own repository which only has a few tags and they're all relevant, so this isn't an issue anymore. The Anitya project was https://release-monitoring.org/project/375107/ but it now tracks this newer repository so isn't a problem anymore.

So pagination was indeed the issue. I get your reasoning, I suppose it's fine to just track newer tags in the future and not bother with existing old tags :shrug:

**Comment by Zlopez** [comment]
I'm glad that you get this solved. The ratelimit is especially annoying when there are plenty of unrelated tags on the repository. And it's only on GitHub.

I'm closing this as fixed as you get it working. Feel free to reopen it if something is still missing.
