### ISSUE TITLE
[privacy] [spam protection] stop putting email addresses somewhere public

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/anitya#205]
Anitya (and any other tool) should never ever put any email address out in the public. Please stop that.
See https://release-monitoring.org/logs and probably even on fedmsg (which is down for me right now).

**Comment by pypingou** [comment]
logs aren't in the public, you need to authenticate for this

**Comment by pypingou** [comment]
but agreed, we could restrict emails to admins only

**Comment by genodeftest** [comment]
Oh, ok. Sorry for the harsh tone then.

**Comment by vivekanand1101** [comment]
As i can derive from [here](https://github.com/fedora-infra/anitya/blob/master/anitya/templates/logs.html#L105), the email is due to `log.description` which takes in `user_mail` as an identifier for the user who made the change or added something new. The other options being `openid`, `fullname` or  `nickname`. So, probably the presence of `user_mail` as the identifier won't be changing.

The other solution is to put a condition on the user - whether he is an admin or not. That we can put an `if..else` before [this](https://github.com/fedora-infra/anitya/blob/master/anitya/templates/logs.html#L99) but, the problem that i am facing is how to present the log for a non-admin without use of the description column in the database.

**Comment by pypingou** [comment]
The thing is, using different openid providers the username or nickname could be the same for two different persons, only the email will remain unique.

So, +1 on changing the logs template and just hide who did the action for non-admin users but we will also need to adjust the message sent to fedmsg to avoid leacking emails and that will require a little more work.

**Comment by vivekanand1101** [comment]
There is a problem with hiding who did the action in changing the log because the email id isn't coming out from a different column in the database but it is coming with the `description`. In the simplest solution, we can hide the description part for non-admins but that would practically mean you are not giving access to logs for them. And, as i said earlier, there is no other column with the help of which you can describe the log.
Are you suggesting to extract and remove the email id part from `description` for non-admins?

**Comment by pypingou** [comment]
>    Are you suggesting to extract and remove the email id part from
>    description for non-admins?

No, this sounds like a bad idea.
I'll need to look into the code and think some more about this

**Comment by genodeftest** [comment]
Thank you!

**Comment by pypingou** [comment]
i don't think this issue got fixed, and I still think it should be fixed :)

**Comment by pypingou** [comment]
So I've been discussing this with @ralphbean and we thought that a good solution would be to use the user's id in the fedmsg message in place of the email and then adjust fedora-infra/fedmsg_meta_fedora_infrastructure to extract the username from this user id if it is of the type `username.id.fedoraproject.org`.
