### ISSUE TITLE
[sourceforge backend] doesn't work on a specific folder release

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/anitya#224]
Anitya fails to get the correct version number for some sourceforge.net projects, e.g. http://sourceforge.net/projects/eclipse-cs

**Comment by pypingou** [comment]
Because it failed for one project doesn't make it true for all of them :)

The backend relies on the RSS feed from sourceforge to find the new version and the project in anitya might need adjustments to this http://sourceforge.net/projects/eclipse-cs/rss?path=/

Note: I'm not seeing any sources released, only ``.jar`` and a ``-bin.zip``, all making me think of binaries.

**Comment by genodeftest** [comment]
> Note: I'm not seeing any sources released, only .jar and a -bin.zip, all making me think of binaries.
You are right, I completely missed that. Feel free to close if you want.

**Comment by pypingou** [comment]
Thanks for checking it :)
