### ISSUE TITLE
Ability to delete "Latest version(s)" when backend/version url/version prefix/regex is updated

### ISSUE THREAD

**Issue by siwinski** [fedora-infra/anitya#257]
I recently updated https://release-monitoring.org/project/6521/ to only track version 1 of the upstream project because version 2 will not be supported in Fedora/EPEL for a while but I do need to track version 1 releases.  Is there a way to delete the old version 2 "Latest version(s)"?  Could either this feature be added or someone manually delete them?

**Comment by pypingou** [comment]
Admins can clean such versions, for this you can either ask here or via the flag mechanism present in the application.

Note though that anitya isn't Fedora specific, so some requests might not be processed because if a project is not followed anymore by anitya doesn't mean it's not followed at all.

**Comment by pypingou** [comment]
Versions 2.* have been removed :)

**Comment by siwinski** [comment]
Thanks @pypingou
