### ISSUE TITLE
ftp protocol unsupported

### ISSUE THREAD

**Issue by rathann** [fedora-infra/anitya#338]
FTP URLs don't work at all, either with "folder" or with "custom" backend. The error I get for https://release-monitoring.org/project/4972/ is:

Could not call : "ftp://ftp.tin.org/pub/news/clients/tin/stable/" of "tin"

**Comment by jeremycline** [comment]
Hey @rathann, thanks for the report!

When I did some experimentation with that particular URL, the server would occasionally close the connection part way through the request. If it didn't, though, the request would work. We could add some retry logic to the FTP request, but it won't solve the underlying problem which is that either the server or someone in between us and the server is halting the TCP connection.

https://github.com/fedora-infra/anitya/pull/376 should at least make it clear from now on _why_ there was an error, and it should occasionally successfully fetch the latest version. If it does fail with something other than "connection reset by peer", please do let us know since there is probably more we can do, but that's all I saw when I was experimenting.
