### ISSUE TITLE
Incorrect version comparison

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/anitya#66]
I just saw [this message](https://apps.fedoraproject.org/datagrepper/id?id=2014-537812ff-66ab-4c98-ba66-b5b988087f8d&is_raw=true&size=extra-large) go by the fedmsg bus, which seems incorrect.

**Comment by ralphbean** [comment]
We need to write a unit test that duplicates this scenario *before* fixing it, so we can be sure we have the case isolated.

**Comment by pypingou** [comment]
The problem:
``
      "old_version": "1.3.0", 
      "upstream_version": "1.0.3",
``
A possible cause is that upstream finally uploaded an older release to pypi (that was missing before)

Another case where we would see this: upstream pushes an older tag to the git repo

In these case, anitya will announce the new release and will say on the website that something odd was found since the new version seems older than the previous latest version.

**Comment by ralphbean** [comment]
So, is any fix needed in anitya?  Or... should we just fix the language generated by fedmsg_meta_fedora_infrastructure?

**Comment by pypingou** [comment]
We can go both ways (but I think I'd like to keep it in anitya, this feature is helpful when a project has bugfix releases for older version, think 1.2.x while 2.y is out), a third option could be to publish a message saying `version.new` instead of `version.update` when the ordering seems odd.

**Comment by ralphbean** [comment]
Yeah, either option sounds good to me.  To restate, either:

- Modify fedmsg_meta_fedora_infrastructure to have a nicer message when old bugfix releases are discovered.
- Modify anitya to send a different kind of message when such bugfix releases are discovered.

(honestly, I prefer option 1 since it will have the least amount of impact on other systems that might already be subscribed to anitya's message stream)

**Comment by pypingou** [comment]
+1 on the first option for me as well :-)


-------- Message d'origine --------
De : Ralph Bean <notifications@github.com> 
Date :10/03/2015  02:33  (GMT+01:00) 
À : fedora-infra/anitya <anitya@noreply.github.com> 
Cc : Pierre-Yves Chibon <pingou@pingoured.fr> 
Objet : Re: [anitya] Incorrect version comparison (#66) 

Yeah, either option sounds good to me. To restate, either:

Modify fedmsg_meta_fedora_infrastructure to have a nicer message when old bugfix releases are discovered.
Modify anitya to send a different kind of message when such bugfix releases are discovered.
(honestly, I prefer option 1 since it will have the least amount of impact on other systems that might already be subscribed to anitya's message stream)

**Comment by ralphbean** [comment]
Noting that this only requires a change to fedmsg_meta now to use that new field to make the description more nice.
