### ISSUE TITLE
Deletion of projects without any reason

### ISSUE THREAD

**Issue by nqb** [fedora-infra/anitya#922]
Hello,

I'm using Anitya since several years. During last months, I noticed that some projects (added by me) have been deleted without any reason.

Examples of applications:
- kanboard
- Miniflux
- pfSense-FreeBSD-ports
- awx

Mail subject received from Fedora Notifications: `anitya deleted the "kanboard" project`

Thanks for your help.

**Comment by Zlopez** [comment]
I did a cleaning a few weeks ago, but deleted only duplicate projects. There is also an automatic deletion of projects, that have no mapping and no version. Do you know if the projects were working correctly?

**Comment by nqb** [comment]
Hello @Zlopez,

> I did a cleaning a few weeks ago, but deleted only duplicate projects.

When you deleted projects, Fedora Notifications send me an email with following subject:

`zlopez deleted the "anitya" project`

Projects were working correctly. I received notifications previously for Kanboard:
```
A new version of "kanboard" has been detected: "1.2.14" newer than "1.2.13", packaged as "(nothing)" (Notification time stamped 2020-04-16 08:50:05 UTC)
A new version of "kanboard" has been detected: "1.2.13" newer than "1.2.12", packaged as "(nothing)" (Notification time stamped 2019-12-16 07:40:28 UTC)
```
Kanboard project has been deleted on 2020-05-23 19:01:37 UTC

**Comment by Zlopez** [comment]
[Here](https://github.com/fedora-infra/anitya/blob/master/anitya/check_service.py#L128) is the function, that is checking if the project is candidate for deletion.

I assume that the projects mentioned above had plenty of failed checks (currently set to 100 on production) and there was no mapping to any distro, which Anitya assumed are a good candidates for deletion.

**Comment by nqb** [comment]
Thanks for your feedback @Zlopez, having a distro mapping is a requirement ? Because some projects can be not packaged on any distro.

**Comment by nqb** [comment]
> I assume that the projects mentioned above had plenty of failed checks (currently set to 100 on production)

How to check that project has failed check s? Kanboard project doesn't seem impacted because I was able to get latest release information recently: 2020-04-16 08:50:05 for 1.12.14 release (latest) and deletion occured one month ago.

**Comment by Zlopez** [comment]
> Thanks for your feedback @Zlopez, having a distro mapping is a requirement ? Because some projects can be not packaged on any distro.

In this case this one goes on me. When I designed this feature, it was because of the flood of fake projects from Pypi and I tried to get rid of them and prevent any future incident. There is only one issue that has impact on this design, if no new version is found the current logic in Anitya is treating this as failed check. Which is probably what happened to your project.

You can see the number of failed checks on the project page in upper right corner, if the check failed.

**Comment by abitrolly** [comment]
So, the history is lost?

**Comment by Zlopez** [comment]
@abitrolly It still should be in the datagrepper.

**Comment by nqb** [comment]
@Zlopez, how can see if projects I mentioned below have been deleted due to failed checks or due to a wrong handle by Anitya ?

**Comment by Zlopez** [comment]
The Anitya only does automatic deletion on number failed checks, this is now set to 100. You can prevent this if you add mapping to distro.

**Comment by nqb** [comment]
This morning I have seen that Packer project had 32 failed checks (I don't know what it means). I login on release-monitoring.org, edit Packer project (without any change) and re-run a check. No more failed check.

Could you explain what does mean a failed check ? In this example, I didn't see why Packer has failed check. Latest release was made two days ago with no difference with the last one.

**Comment by Zlopez** [comment]
In this case it's bug, if there is no new version retrieved it is marked as failed check on project with GitHub backend. This bug was unfortunately introduced when we started using cursors when checking for new versions. I noticed that there isn't any ticket for this issue, so I created it https://github.com/fedora-infra/anitya/issues/929.

Otherwise the failed check means that there was some issue when retrieving the list of versions. This could be a temporary issue like server outage or something more sinister like project no longer exists. I introduced this to automatically delete dummy projects sometimes created based on the SSE reader from libraries.io.

In current settings if Anitya hits 100 failed checks it deletes the project if it doesn't have any distribution mapping.

**Comment by nqb** [comment]
Thanks @Zlopez for your detailed answers on this issue.

My guess is that all projects mentioned previously where created by me without any distribution mapping and they use GitHub backend. Due to missing distribution mapping and #929, they have certainly been deleted.

I will recreate them once #929 is fixed because some projects like Kanboard are not packaged.

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/88070119-9ed9b700-cb72-11ea-9a2b-3ac1047be423.png)
I've also received an email just now that a project (which I actually maintain) was deleted from anitya. It isn't present in the repos of distros other than Debian (for many others we have separate package repos mostly on OBS (open build service)). I don't know if I added a 'distro mapping' for that project but it definitely shouldn't have been deleted automatically.

**Comment by z3ntu** [comment]
The project is hosted on GitHub

**Comment by Zlopez** [comment]
In this case, it's the issue https://github.com/fedora-infra/anitya/issues/929. As a temporary workaround I can recommend to create a dummy distro mapping.

**Comment by z3ntu** [comment]
Imo the automatic deletion should be disabled asap on prod so that no other projects get falsely deleted. Most 'projects' on anitya I've seen don't have any distro mappings so this could get bad if it decides to "randomly" delete projects

**Comment by Zlopez** [comment]
The decision is not random, it's based on the counter of checks for new version that failed. But I will disable this for now to prevent the false deletion.

**Comment by Zlopez** [comment]
I [set](https://pagure.io/fedora-infra/ansible/pull-request/170) the deletion threshold to very big value, it will take 10 years for constantly failing project to reach this.

Just for info here is the description of the method that is marking the projects as candidates for deletion:
```    
Check if this project is a candidate for deletion. Project is a candidate for
deletion, if error_counter already reached configured threshold and project
has no mapping. If mapping exists, but project doesn't have any versions it's
still a candidate for deletion.
```
It was created because of the flood of bogus projects at one time. The error_counter is cleared each time the new version is successfully retrieved.
