### ISSUE TITLE
github seems to fail since new homepage layout

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/anitya#942]
github has a new page layout and it seems that we do some kind of scraping the webpage instead of using the api (i assume the api did not change, might be wrong).

examples:
https://release-monitoring.org/project/44529/
https://release-monitoring.org/project/16871/

**Comment by Zlopez** [comment]
We are using the GraphQL API, there isn't any scrapping for GitHub projects.
The issue you see https://github.com/fedora-infra/anitya/issues/929 and it affects the GitHub especially, because there was enhancement that is using cursor instead of obtaining every version each time. This is helping with the ratelimit, but introduced this new issue with no upstream found version.

I'm closing this now, feel free to reopen it.
